/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : RL78G15_General.c
*  Description  : Main Program
*  Creation Date: 2024-02-23
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include<string.h>
#include<stdlib.h>
#include "UART0.h"
#include "IO_PORT.h"

int main (void);
void intToString(int,char*);
void doubleToString(double,char*,int);
void lcd_hole_draw(const char*,const char*);
void lcd_print(const char *);
void lcd_init(void);
void lcd_set_cursor(uint8_t, uint8_t);
void lcd_4bit_Send(uint8_t);
void lcd_8bit_Send(uint8_t);
void lcd_Inst(uint8_t);
void lcd_Data(uint8_t);

#define RS 2,1 //P21
#define EN 2,0 //P20
#define D4 2,2 //P22
#define D5 2,3 //P23
#define D6 0,7 //P07
#define D7 0,6 //P06

#pragma address (rx_buf = 0x0ffe00)

int main(void)
{
    EI();
    R_Pwm_Start();
    char command[8]="";
    char ad_result[20]="";
    char rx_buf[1]="";
    char row1_data[16]="";
    char row2_data[16]="";
    int count=0;
    R_UART0_Start();
    lcd_init();

    while(1){
    	count++;
    	intToString(count,row2_data);
    	uart_receive(rx_buf);
    	strcat(row1_data,rx_buf);
    	if(rx_buf[0]=='|'){
    		strcpy(row1_data,"");
    	}
    	lcd_hole_draw(row1_data,row2_data);
        //ms_wait(1);

        /*
    	/////////////uart通信によるコマンド受信でモード変更するための初歩的なコード//////////
    	uart_receive(command);
    	if(strcmp(command,"res")==0){
    		uart_send("reset");
    	}
    	if(strcmp(command,"app")==0){
    		uart_send("application");
    	}
    	if(strcmp(command,"ad1")==0){
    		strcpy(ad_result,"");
    		intToString(123,ad_result);
    		uart_send(ad_result);
    	}
    	if(strcmp(command,"ad2")==0){
    		strcpy(ad_result,"");
    		doubleToString(3.1415,ad_result,3);
    		uart_send(ad_result);
    	}else{
    		;
    	}*/
    	//////////////////////////////////////////////////////////////////
    }
}

void intToString(int num, char* result) {
	// 結果を格納するためのバッファ
    char buffer[20];  // 十分な大きさを確保
    strcpy(result,"");

    // 数字を文字列に変換
    int index = 0;
    if (num == 0) {
        buffer[index++] = '0';
    } else {
        // numが0でない場合、各桁を文字に変換して逆順にバッファに格納
        while (num != 0) {
            int digit = num % 10;
            buffer[index++] = '0' + digit;
            num /= 10;
        }
    }

    // バッファの内容を逆順にresultにコピー
    int i;
    for (i = 0; i < index; ++i) {
        result[i] = buffer[index - i - 1];
    }

    // 終端文字を追加
    result[i] = '\0';
}
void doubleToString(double num, char* result, int precision) {
    // 整数部分と小数部分の一時的なバッファ
    char integerBuffer[20];
    char decimalBuffer[20];

    // 整数部分を文字列に変換
    int integerPart = (int)num;
    intToString(integerPart, integerBuffer);

    // 小数部分を文字列に変換
    double decimalPart = num - integerPart;
    int i;
    for (i = 0; i < precision; ++i) {
        decimalPart *= 10;
        decimalBuffer[i] = '0' + (int)decimalPart;
        decimalPart -= (int)decimalPart;
    }

    // 文字列を手動で結合して結果に格納
    int resultIndex = 0;
    int bufferIndex;
    for (bufferIndex = 0; integerBuffer[bufferIndex] != '\0'; ++bufferIndex) {
        result[resultIndex++] = integerBuffer[bufferIndex];
    }

    // 小数点を挿入
    result[resultIndex++] = '.';

    // 小数部分を追加
    for (i = 0; i < precision; ++i) {
        result[resultIndex++] = decimalBuffer[i];
    }

    // 終端文字を追加
    result[resultIndex] = '\0';
}

void lcd_hole_draw(const char *text1,const char *text2){
	lcd_Inst(0b00000001);
	ms_wait(2);
    lcd_set_cursor(0,0);
    lcd_print(text1);
    lcd_set_cursor(1,0);
    lcd_print(text2);
}

void lcd_print(const char *text) {
    while (*text != '\0') {
        lcd_Data(*text++);
    }
}

void lcd_init(void) {
	digitalWrite(RS,0);
	digitalWrite(EN,0);
	ms_wait(50);
    lcd_4bit_Send(0b0011);// Function Set
    ms_wait(5);
    lcd_4bit_Send(0b0011);// Function Set
    us_wait(15);
    lcd_4bit_Send(0b0011);// Function Set
    lcd_4bit_Send(0b0010);// Function Set
    us_wait(40);
    lcd_Inst(0b00101000);// 4-bitモードへの設定
    lcd_Inst(0b00001000);// Display OFF
    lcd_Inst(0b00000001);// Clear Display
    ms_wait(2);
    lcd_Inst(0b00000110);// Entry Mode Set
    lcd_Inst(0b00001100);// Display ON

}

void lcd_4bit_Send(uint8_t command){
	digitalWrite(EN,1);
    // 下位4ビット送信
    digitalWrite(D4, (command) & 0x01);
    digitalWrite(D5, (command >> 1) & 0x01);
    digitalWrite(D6, (command >> 2) & 0x01);
    digitalWrite(D7, (command >> 3) & 0x01);
    us_wait(5);
    digitalWrite(2,0,0);
}

void lcd_8bit_Send(uint8_t command){
	lcd_4bit_Send(command>>4);
	lcd_4bit_Send(command);
}

void lcd_Inst(uint8_t command){
	digitalWrite(RS,0);
	lcd_8bit_Send(command);
	us_wait(4);
}

void lcd_Data(uint8_t data){
	digitalWrite(RS,1);
	lcd_8bit_Send(data);
	us_wait(4);
}

void lcd_set_cursor(uint8_t row, uint8_t col) {
    // 行ごとに特定のオフセットが必要な場合があるので、データシートを確認してください
    uint8_t offsets[] = {0x00, 0x40};

    if (row < 2 && col < 16) {
        uint8_t position = col + offsets[row];
        lcd_Inst(0x80+position);
    }
}
